---
- name: template foreman settings.yaml
  template:
    src=settings.yaml.j2
    dest=/etc/foreman/settings.yaml
    backup=yes

- name: configure foreman init config
  replace:
    dest=/etc/default/foreman
    regexp="START=no"
    replace="START=yes"
  when: ansible_os_family == "Debian" and foreman_enable_service
